// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSeminarioControlNotas.Models;

#nullable disable

namespace ProyectoSeminarioControlNotas.Migrations
{
    [DbContext(typeof(ProyectoDbContext))]
    [Migration("20240929215713_nuevosModelos")]
    partial class nuevosModelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoSeminarioControlNotas.Models.Alumno", b =>
                {
                    b.Property<int>("idAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAlumno"));

                    b.Property<int?>("CarreraidCarrera")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("carrera")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("estadoAlumno")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("fechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("numeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("idAlumno");

                    b.HasIndex("CarreraidCarrera");

                    b.ToTable("alumnos");
                });

            modelBuilder.Entity("ProyectoSeminarioControlNotas.Models.Carrera", b =>
                {
                    b.Property<int>("idCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCarrera"));

                    b.Property<string>("codigoCarrera")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("estadoCarrera")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("numeroCiclo")
                        .HasColumnType("int");

                    b.HasKey("idCarrera");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("ProyectoSeminarioControlNotas.Models.Curso", b =>
                {
                    b.Property<int>("idCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCurso"));

                    b.Property<int>("Ciclo")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("idCurso");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("ProyectoSeminarioControlNotas.Models.Alumno", b =>
                {
                    b.HasOne("ProyectoSeminarioControlNotas.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraidCarrera");

                    b.Navigation("Carrera");
                });
#pragma warning restore 612, 618
        }
    }
}
